#!/bin/bash

function print_help {
	echo "usage:"
	printf "\tmyserver start # to start the server\n"
	printf "\tmyserver stop # to stop the server\n"
}

#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
DIR=$HOME/.local/myserver/
if [ $# -lt 1 ]; then
	 print_help
	 exit 
fi
if [ $1 == "start" ]; then
	setsid python3 -u $DIR/main.py > $DIR/socket_server.log 2>&1 </dev/null & 
	echo $! > $DIR/pid.txt
	setsid php -S 0.0.0.0:8080 -t $DIR > $DIR/php.log 2>&1 </dev/null & 
	echo $! >> $DIR/pid.txt
	echo "runing in $DIR"
	
elif [ $1 == "stop" ]; then
	while IFS= read -r var
	do
	  kill $var
	done < "$DIR/pid.txt";
	if [ -f $DIR/pid.txt ]; then 
		rm $DIR/pid.txt
	fi
	echo "shut down"
else
	print_help
fi

